l_english:
 upgrade_building_macro_settings_event.1.t: "Upgrade Building Macro Settings"
 upgrade_building_macro_settings_event.1.d: "Here you can fine tune how the Upgrade Building Macro upgrade buildings."
 upgrade_building_macro_settings_event.1.a: "Configure Upgrade Quantity"
 upgrade_building_macro_settings_event.1.b: "Misc Settings"
 upgrade_building_macro_settings_event.2.t: "Configure Upgrade Quantity"
 upgrade_building_macro_settings_event.2.d: "Here you can configure how many buildings are upgraded at a time whenever you click a button on the macro builder.\n\nThe §Ghighlighted§! option indicates which option is currently selected."
 upgrade_building_macro_settings_event.2.infinite: "Upgrade the Maximum Amount of Buildings Possible"
 upgrade_building_macro_settings_event.2.build_1: "Upgrade 1 Building at a Time"
 upgrade_building_macro_settings_event.2.build_5: "Upgrade 5 Buildings at a Time"
 upgrade_building_macro_settings_event.2.build_10: "Upgrade 10 Buildings at a Time"
 upgrade_building_macro_settings_event.2.build_25: "Upgrade 25 Buildings at a Time"
 upgrade_building_macro_settings_event.2.build_50: "Upgrade 50 Buildings at a Time"
 upgrade_building_macro_settings_event.3.t: "Misc Settings"
 upgrade_building_macro_settings_event.3.d: "Here you can find a variety of different settings for the macro builder that fall into a single category.\n\nIf the option is §Ghighlighted§!, it means it's enabled."
 upgrade_building_macro_settings_event.3.a: "Toggle Smart Upgrading"
 smart_build_building_macro_tt: "Disabling smart building will lead to a §Glarge increase§! in §Yperformance§! when §Ybuilding§!, but it will make the macro build in §Rany province§! that has an open building slot rather than the most optimal one."
 smart_upgrade_macro_tt: "Disabling smart upgrading will lead to a §Glarge increase§! in §Yperformance§! when §Yupgrading§!, but it will make the macro build in §Rany province§! that has a building that can be upgraded rather than the most optimal one."